# Generated by Django 4.1.7 on 2023-04-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
