# Generated by Django 4.1.7 on 2023-05-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='numtel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
